name: 🎨 Paint a Pixel
description: Paint a pixel on the canvas
title: "Paint [A1] #FFFFFF"
labels: []

body:
  - type: input
    id: note
    attributes:
      label: Optional message
      placeholder: (optional)
    validations:
      required: false
